// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3Uv746itKiYZSQ4rDcgowQIV_ustiaU',
    appId: '1:275171120353:web:4f9dec1a4828b763fe53a0',
    messagingSenderId: '275171120353',
    projectId: 'cmsc23-week9',
    authDomain: 'cmsc23-week9.firebaseapp.com',
    storageBucket: 'cmsc23-week9.appspot.com',
    measurementId: 'G-E538T7P57P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBn0ANFUSYAXbfQXTN0TVYd1u4Zq4kyI4',
    appId: '1:275171120353:android:4d57fceb1aff6914fe53a0',
    messagingSenderId: '275171120353',
    projectId: 'cmsc23-week9',
    storageBucket: 'cmsc23-week9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS-kZG4FTtIHd_YksboQ5AqTa9kjdSLg4',
    appId: '1:275171120353:ios:cc739d1d72420ba8fe53a0',
    messagingSenderId: '275171120353',
    projectId: 'cmsc23-week9',
    storageBucket: 'cmsc23-week9.appspot.com',
    iosClientId: '275171120353-jhqtj3blupo6md441an7o30qgpakshrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS-kZG4FTtIHd_YksboQ5AqTa9kjdSLg4',
    appId: '1:275171120353:ios:cc739d1d72420ba8fe53a0',
    messagingSenderId: '275171120353',
    projectId: 'cmsc23-week9',
    storageBucket: 'cmsc23-week9.appspot.com',
    iosClientId: '275171120353-jhqtj3blupo6md441an7o30qgpakshrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
